name: First Github Workflow

on:
  push:
      branches: [ "actions_test_1", "develop" ]
  pull_request:
      branches: [ "main" ]

  workflow_dispatch: 

jobs:
  first-job:
    runs-on: ubuntu-latest
    container: 
      image: alpine:3.19
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for alphine image
        run: |
          apk add --no-cache coreutils
          apk add lsb-release
          echo " Which user you are ? "
          whoami
          echo " Your OS type ?"
          cat /etc/os-release

      - name: Print single line script as step 1
        run: echo Hello, world!
        
      - name: Print multi line script as step 2
        run: |
          echo "Listing all files in the github repository"
          ls -lta
          echo "Add other actions to build,"
          echo "test, and deploy your project."
