name: First Github Workflow

on:
  push:
      branches: [ "actions_test_1", "develop" ]
  pull_request:
      branches: [ "main" ]

  workflow_dispatch: 

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print single line script as step 1
        run: echo Hello, world!
        
      - name: Print multi line script as step 2
        run: |
          echo "Listing all files in the github repository"
          ls -lt
          echo "Add other actions to build,"
          echo "test, and deploy your project."
